### ISSUE TITLE
add configuration variable for setting owlapi_wrapper java heap size

### ISSUE THREAD

**Issue by alexskr** [ncbo/ontologies_linked_data#124]
The java heap size for running owlapi_wrapper is currently hardcoded to 10GB which might not be sufficient for large ontologies such as NCBITAXON.   A new configuration variable needs to be added for changing the default java heap size.

**Comment by syphax-bouazzouni** [comment]
Hi we have the same issue at agroportal (see https://github.com/ontoportal-lirmm/ontologies_linked_data/issues/15).
Have you made any progress on this ?
