### ISSUE TITLE
Blank labels (no preferred names)

### ISSUE THREAD

**Issue by shawntanzk** [ncbo/ontologies_linked_data#137]
Related to: https://github.com/ncbo/ontologies_linked_data/issues/125

Many nodes do not have preferred name and are hence showing up blank for PCL:

![Screenshot 2022-04-06 at 17 15 28](https://user-images.githubusercontent.com/76212760/162020403-51540289-4278-4fe9-9cc7-c07ce6d27f00.png)

Interestingly, the same term in CL (CL_0000000) shows up perfectly fine there: 

![Screenshot 2022-04-06 at 17 16 55](https://user-images.githubusercontent.com/76212760/162020673-2facbd64-bedb-44d2-b44d-ab2fbc35abac.png)

A few things we have also noticed:

- when trying to select the blank class, bioportal gets stucked at "loading class"
- one hypothesis we have is that the blank classes lack xsd:string type (but they do show up in CL, so maybe its a mix) - hard to verify this as we cant load any class that is blank except the one we land on which is "cell" as above

Tagging @dosumis @hkir-dev @scheuerm 

Thanks :)

**Comment by jvendetti** [comment]
@shawntanzk - it appears that there was a processing error on our side when the latest version of PCL was uploaded. I've reprocessed the latest submission and it's now fully available in BioPortal. You may need to refresh your browser window to see the labels. Apologies for the inconvenience.

![Screen Shot 2022-04-06 at 10 49 54 AM](https://user-images.githubusercontent.com/1696923/162037443-7291d510-9b7d-400d-86ea-087c37ba164f.png)

**Comment by shawntanzk** [comment]
Thanks heaps! looks perfect :)
