### ISSUE TITLE
Remove abandoned test-unit-minitest gem in favor of minitest

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_linked_data#147]
The [test block in the Gemfile](https://github.com/ncbo/ontologies_linked_data/blob/fc90752c9476cdbd06b102577aec2f9110fbce8d/Gemfile#L29) has a dependency on [test-unit-minitest](https://rubygems.org/gems/test-unit-minitest), which appears to have been abandoned in 2015. 

The test-unit-minitest gem requires minitest 4.7, which is very old (from 2013).

test-unit-minitest should be replaced in favor of using the latest version of [minitest](https://rubygems.org/gems/minitest). One of the main motiviations for this is that RubyMine's support for minitest requires minitest version 5.0 or above. Our ability to use a decent IDE for debugging ontologies_linked_data code is adversely effected by the presence of the outdated test-unit-minitest gem.

**Comment by alexskr** [comment]
resolved by https://github.com/ncbo/ontologies_linked_data/pull/168
