### ISSUE TITLE
Add GitHub username and ORCID iD as attributes on the User model

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_linked_data#160]
The driver behind this request is Aim 3 of the BioPortal U24 grant. We're adding functionality that allows BioPortal users to request changes to ontologies when those ontologies are managed/hosted in GitHub. 

Each change request entered via the [BioPortal web application](https://bioportal.bioontology.org/) will be propagated as a GitHub issue in the repository where the ontology is hosted. As part of the body of the issue text, we'd like to use GitHub's syntax that allows you to combine the @ symbol with a GitHub username to mention someone. In our case, that someone would be the BioPortal user that requested the ontology change. For example, the issue body might contain something like the following:

> Change request auto-generated from BioPortal on behalf of @jvendetti

Mentioning someone in this way would allow us to take advantage of GitHub's built-in functionality that notifies the person they have been mentioned in an issue.

In order to do something like this, we need to be able to allow end users to optionally enter their GitHub username when they create a BioPortal account.

Adding the ORCID iD is secondary in terms of importance, but I think it would make sense to add these at the same time.

**Comment by jvendetti** [comment]
For those without an AgroPortal API key, this is a sample of what the results look like from Clement's link in the previous comment:

```json
{
  "repository": "https://sourceforge.net/projects/geneontology/",
  "bugDatabase": "https://github.com/geneontology/go-ontology/issues/",
  "@id": "http://data.agroportal.lirmm.fr/ontologies/GO/submissions/206",
  "@type": "http://data.bioontology.org/metadata/OntologySubmission"
},
{
  "repository": null,
  "bugDatabase": null,
  "@id": "http://data.agroportal.lirmm.fr/ontologies/WHEATPHENOTYPE/submissions/9",
  "@type": "http://data.bioontology.org/metadata/OntologySubmission"
},
{
  "repository": "https://xeo.codeplex.com/SourceControl/latest",
  "bugDatabase": "https://xeo.codeplex.com/workitem/list/basic",
  "@id": "http://data.agroportal.lirmm.fr/ontologies/XEO/submissions/1",
  "@type": "http://data.bioontology.org/metadata/OntologySubmission"
}
```

**Comment by jvendetti** [comment]
Hi @syphax-bouazzouni. Thank you very much for the feedback. I'm not sure I followed precisely your proposal. Is this referring to the general topic of implementing SSO for BioPortal/OntoPortal?

**Comment by jvendetti** [comment]
Thank you for the information about your metadata model @jonquet. I've been working on Aim 3 for the U24 grant in a topic branch called [kgcl-change-requests](https://github.com/ncbo/bioportal_web_ui/tree/kgcl-change-requests). At the moment, I'm using a YAML configuration file to store the repositories associated with ontologies. I needed the ability to specify different repositories for each ontology depending on what mode our Rails application is running in:

https://github.com/ncbo/bioportal_web_ui/blob/kgcl-change-requests/config/change_request.yml

This also allowed me to take advantage of Rails built-in support for custom configuration:

https://guides.rubyonrails.org/configuring.html#custom-configuration

It's high on my to-do list to merge the topic branch into master to facilitate feedback and possible collaboration.

**Comment by graybeal** [comment]
See also https://github.com/ncbo/bioportal-project/issues/134 for a corollary task that would be valuable to include at this time.
