### ISSUE TITLE
redis-rb v4.8.0 compatibility issue

### ISSUE THREAD

**Issue by alexskr** [ncbo/ontologies_linked_data#163]
We are getting the following warnings/notifications when running unit tests for ontologies_api.  This warning doesn't pop up when running unit tests on the ontologies_linked_data.  

```
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /srv/ontoportal/bundle/ruby/2.7.0/bundler/gems/ontologies_linked_data-4f9139d870c3/lib/ontologies_linked_data/http_cache/cacheable_resource.rb:159:in `cache_write')
```

Are we not testing cacheable resources? in ontologies_linked_data?

**Comment by jvendetti** [comment]
Cacheable resources (including the `cache_write` method) are unit tested in ontologies_linked_data:

https://github.com/ncbo/ontologies_linked_data/blob/4f9139d870c3b1771af1127afa17b679bd0f60dc/test/http_cache/test_http_cache.rb.

**Comment by alexskr** [comment]
relates to https://github.com/ncbo/ontologies_api/issues/105.    
ontologies_linked_data redis gem is on v5+ while ontologies_api is on v4.  
https://github.com/ncbo/ontologies_api/pull/120 addresses this issue
