### ISSUE TITLE
Notifications: ontology processing notification sends out misleading email about failed archived submission

### ISSUE THREAD

**Issue by alexskr** [ncbo/ontologies_linked_data#185]
PR https://github.com/ncbo/ontologies_linked_data/pull/184 and https://github.com/ncbo/ontologies_linked_data/pull/148 restored new ontology submission processing notifications.  When new submission is processed OntoPortal sends two notifications:
1 Success:
![image](https://github.com/ncbo/ontologies_linked_data/assets/1591816/c6e67095-660b-41b9-b125-fe4ceeef6557)
2: Failure for archived
![image](https://github.com/ncbo/ontologies_linked_data/assets/1591816/537f0df1-1d0e-4c01-8b63-769ef16a8688)

Archive notification gets incorrectly flagged as a failure because archived submission is no longer [ready](
https://github.com/ncbo/ontologies_linked_data/blob/247fb4daa499af1a8c2d71064734c1b703bcdb71/lib/ontologies_linked_data/utils/notifications.rb#L36).   The second notification about archived submission should not be send out because it might confuse users and I don't think users are interested in getting that information in the first place.

**Comment by syphax-bouazzouni** [comment]
Here is a commit that we did at Agroportal to fix that https://github.com/ontoportal-lirmm/ontologies_linked_data/pull/116/commits/6af858ab82cb386cc11f29451842f42a5d5104cb

You can copy the fix if it is good for you

**Comment by alexskr** [comment]
Thanks @syphax-bouazzouni, https://github.com/ncbo/ontologies_linked_data/commit/602a44cbe83ff13d304650f3c4352497d0071a8a fixed the issue
 with the email title with the notifications about archived submissions.  
 However, do users even need to know that the previous submission was archived?

**Comment by alexskr** [comment]
relates to https://github.com/ncbo/bioportal-project/issues/291
