### ISSUE TITLE
Notifications sends separate emails for archived status with vague content

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_linked_data#190]
I'm listed as an administrator for the [ARO](https://bioportal.bioontology.org/ontologies/ARO) ontology. I got an email at 6:03pm that a new version was processed with a title of "Antibiotic Resistance Ontology Parsing Success". The content is:

```
Antibiotic Resistance Ontology (ARO) was processed for use in BioPortal. Here are the results:

Parsed successfully
Indexed terms for search
Indexed properties for search
Class metrics calculated
Created submission version diff successfully
...
```

I got a second email (also at 6:03pm) with the identical title of "Antibiotic Resistance Ontology Parsing Success". The content is:

```
Antibiotic Resistance Ontology (ARO) was processed for use in BioPortal. Here are the results:

Archived
...
```

Since I know BioPortal's internals, I read this and understood that since a new submission was uploaded, we archived the previous submission. However, there are lots of BioPortal users who administer ontologies and don't know anything about our internals. I find the content potentially confusing to users who might wonder what archived is even referring to with regard to their ontology. I also don't think we should generate multiple messages when new submissions are processed.

**Comment by alexskr** [comment]
see also https://github.com/ncbo/ontologies_linked_data/issues/185#issuecomment-1930725367

**Comment by alexskr** [comment]
relates to https://github.com/ncbo/bioportal-project/issues/291

**Comment by jvendetti** [comment]
Production was rolled back on May 8th to v5.29.1. This behavior is occurring again. Reopening this as a reminder to make sure the fixes are correctly re-deployed.
