### ISSUE TITLE
Missing unit test for IRI extraction

### ISSUE THREAD

**Issue by alexskr** [ncbo/ontologies_linked_data#200]
We are missing the unit test for IRI extraction introduced in 
https://github.com/ncbo/ontologies_linked_data/pull/153

It is indirectly tested by OBO ID search, which relies on IRI; however, a direct unit test would provide more clarity.

**Comment by syphax-bouazzouni** [comment]
this PR https://github.com/ncbo/ontologies_linked_data/pull/199 includes a unit test for the extraction step  called test_extraction_metadata(https://github.com/ncbo/ontologies_linked_data/pull/199/files#diff-a121859f7a845ade0d5d33bb88b4fea2511f9c9d31b99aad291006f5ce20398dR1152)

**Comment by alexskr** [comment]
great!  thanks!
