### ISSUE TITLE
Empty pages in paged result sets

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_linked_data#66]
User reported on the mailing list that this REST call:

http://data.bioontology.org/mappings?ontologies=MESH,MP

... returns a result set with a page count of 27.  However, all pages after page 8 are empty.  This is reproducible in production.

Empty pages in paged result sets from REST calls have been happening as far back as October of 2015.  BioPortal team members with access to the old private JIRA issue tracker, see NCBO-1523.

**Comment by jvendetti** [comment]
Clearing the goo and HTTP caches has no effect on this issue.

**Comment by mdorf** [comment]
This has been fixed. See #115.
