### ISSUE TITLE
SKOS Event and GeoCoordinates (schema.org) individuals are not returned by the core API

### ISSUE THREAD

**Issue by mdorf** [ncbo/ontologies_linked_data#83]
Per Michelle Futornick:

The vocabularies in question are called FAST (Faceted Application of Subject Terminology) and are produced by OCLC (http://experimental.worldcat.org/fast/)

The OCLC FAST vocabularies use SKOS and schema.org, and this seems to be part of the problem BioPortal is having with handling these vocabularies. 

For example, in the FAST-EVENT-NT vocabulary, there are 686 individuals that are members of class <http://www.w3.org/2004/02/skos/core#Concept> and 15,007 individuals that are members of <http://schema.org/Event> (also 1283 that are members of <http://schema.org/GeoCoordinates>)

Yes the BioPortal search works, but only finds those individuals typed as skos/core#Concept, and not the individuals typed as schema.org/Event

Here's an example to illustrate. There are two individuals in FAST EVENT that contain the word 'horseshoe' in their label. One is a skos/Concept, one is a schema.org/Event:

(1)
<http://id.worldcat.org/fast/960725> <http://www.w3.org/2004/02/skos/core#prefLabel> "Horseshoe Bend, Battle of (Alabama : 1814)" .
<http://id.worldcat.org/fast/960725> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Event> .

(2)
<http://data.bnf.fr/ark:/12148/cb13567739b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> .
<http://data.bnf.fr/ark:/12148/cb13567739b> <http://www.w3.org/2000/01/rdf-schema#label> "Horseshoe Bend, Bataille de (1814)" .

Searching for horseshoe finds only 1 result, the one typed skos/Concept: 
http://data.bioontology.org/search?q=horseshoe&ontologies=FAST-EVENT-SKOS
"totalCount": 1
prefLabel": "Horseshoe Bend, Bataille de (1814)"

**Comment by graybeal** [comment]
I think we may have overlooked responding to this issue; I'm going to update it based on my recollection of our analysis. @mdorf , please see if you agree that my response is accurate, and close this issue if appropriate. Thanks.

This ontology is mixing SKOS with other content that is based on classes. While we can handle an ontology that is pure SKOS, we can not work with one that is mixed SKOS and class concepts. This is not a common practice in the semantic community, so it is unlikely we would try to adapt to it for BioPortal.

**Comment by graybeal** [comment]
oops, didn't mean to hit the close button so soon...

**Comment by jvendetti** [comment]
@graybeal - you are correct. BioPortal handles SKOS vocabularies, but offers no support for Schema.org vocabularies. Hence, the behavior that Michelle describes above where skos:Concept declarations are recognized by the system, but Schema.org Event declarations aren't. @misha - if you disagree, feel free to reopen.
