### ISSUE TITLE
Incorrect mapping counts reported

### ISSUE THREAD

**Issue by mdorf** [ncbo/ontologies_linked_data#88]
In order to avoid the expensive COUNT queries to 4store, we've implemented a system, where mapping counts get generated by a CRON process that runs weekly.  There appears to be a bug in this code that creates a discrepancy between the generated count and the actual number of mappings when retrieved via the REST service. Examples:

http://data.bioontology.org/mappings?ontologies=EXACT,EP
http://data.bioontology.org/mappings?ontologies=EXACT,CLO

<img width="472" alt="screen shot 2018-10-19 at 4 51 53 pm" src="https://user-images.githubusercontent.com/2042070/47248445-569acd00-d3bf-11e8-99f4-969632137aa0.png">

Reference code is found here:
https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/mappings/mappings.rb#L75

Corresponding list in the UI:
<img width="863" alt="Screen Shot 2021-03-10 at 1 26 26 PM" src="https://user-images.githubusercontent.com/1266896/110700096-6986e580-81a4-11eb-9420-6120951c8196.png">

**Comment by graybeal** [comment]
Duplicate of #115, which is now fixed.
