### ISSUE TITLE
create_mapping_counts method persists null values for some ontologies

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_linked_data#89]
Issuing the following REST call:

http://data.bioontology.org/mappings/statistics/ontologies

... produces a result set where the IAML-MOP and EITOUT ontologies have null entries for the mapping count.

![screenshot 2018-10-23 12 57 50](https://user-images.githubusercontent.com/1696923/47387160-65d19180-d6c3-11e8-937e-5a1977053efa.png)

This caused the [mappings page](http://bioportal.bioontology.org/mappings) in the BioPortal UI to fail because there was no check for null values. I would expect that if no mappings exist, the column would contain 0.

If you issue separate calls to retrieve mapping counts for the above mentioned ontologies, the REST endpoint returns count data instead of null values.

http://data.bioontology.org/mappings/statistics/ontologies/IAML-MOP
http://data.bioontology.org/mappings/statistics/ontologies/EITOUT

![screenshot 2018-10-23 13 10 57](https://user-images.githubusercontent.com/1696923/47387749-1a1fe780-d6c5-11e8-966a-ee6afebfc375.png)

**Comment by graybeal** [comment]
This is no longer a problem, likely due to the fixes in #115 and similar.
