### ISSUE TITLE
Incorrect mapping count statistics generated for some ontologies

### ISSUE THREAD

**Issue by mdorf** [ncbo/ontologies_linked_data#94]
http://data.bioontology.org/mappings/statistics/ontologies/LUNGMAP-HUMAN
```
{
    "KTAO": 13,
    "FOODON": 1,
    "MSTDE": 1,
    "OGG": 1
}
```
This data is displayed in the UI:
https://bioportal.bioontology.org/ontologies/LUNGMAP-HUMAN/?p=mappings

<img width="1134" alt="Screen Shot 2021-03-10 at 2 09 46 PM" src="https://user-images.githubusercontent.com/1266896/110704769-4a8b5200-81aa-11eb-85b9-8361872d82dd.png">

http://data.bioontology.org/mappings/statistics/ontologies/LUNGMAP-MOUSE
```
{
    "OGG": 2,
    "MSTDE": 2,
    "FOODON": 1,
    "KTAO": 15,
    "ODNAE": 1
}
```
This data is displayed in the UI:
https://bioportal.bioontology.org/ontologies/LUNGMAP-MOUSE/?p=mappings

<img width="711" alt="Screen Shot 2021-03-10 at 2 10 45 PM" src="https://user-images.githubusercontent.com/1266896/110704871-6bec3e00-81aa-11eb-8b80-93a6bd76d7ab.png">

Both ontologies have thousands of mappings to many more ontologies than the output above indicates. This is evident by calling the mappings endpoints:
http://data.bioontology.org/ontologies/LUNGMAP-HUMAN/mappings
http://data.bioontology.org/ontologies/LUNGMAP-MOUSE/mappings

**Comment by mdorf** [comment]
The suspect code is `def self.create_mapping_counts(logger)`, located here:
https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/mappings/mappings.rb#L589

**Comment by graybeal** [comment]
The number of mappings shown for these two endpoints as of today is 4127 and 5807. 

The number of mappings between LUNGMAP-HUMAN and LUNGMAP-MOUSE is shown in API and UI as 226. 

This is now resolved, likely due to the work completed recently on #115.

**Comment by mdorf** [comment]
resolved, deployed
