### ISSUE TITLE
Generated link to reset password uses insecure protocol

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_linked_data#98]
Reported by an end user:

> FYI, the link below is HTTP and not HTTPS...
>
> admin@bioontology.org wrote on 12/4/19 6:34 PM:
Someone has requested a password reset for user xxx. If this was you, please click on the link below to reset your password. Otherwise, please ignore this email.
>
> http://bioportal.bioontology.org/reset_password

We're hard-coding the HTTP protocol in the [reset_password](https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/utils/notifications.rb#L106) method.

**Comment by andrew-nguyen** [comment]
It would also be helpful if http://bioportal.bioontology.org redirected automatically to https.  Thanks!

**Comment by andrew-nguyen** [comment]
Another related issue is the token never seems to expire (either after a certain amount of time or after being used once).  I just clicked on the link that was generated over a week ago and was able to arbitrarily reset my password again.

**Comment by jvendetti** [comment]
> Another related issue is the token never seems to expire (either after a certain amount of time or after being used once).

I entered a separate issue for this, as the code that generates the tokens lives in a different repository. See https://github.com/ncbo/ontologies_api/issues/60.

**Comment by jvendetti** [comment]
> It would also be helpful if http://bioportal.bioontology.org redirected automatically to https

Yes, we agree. See relevant issues:

https://github.com/ncbo/bioportal-project/issues/83
https://github.com/ncbo/biomixer/issues/2

**Comment by jvendetti** [comment]
Fixed with this commit: https://github.com/ncbo/ontologies_linked_data/commit/78fa10a374246e30add202d4fc1464373403d2e0
